package org.vollgaz.sas.models

import scala.xml.{Elem, Node}

/**
  * Represents library object. Libraries are used to contains datasets. You can consider Libraries as databases and datasets as databases' tables.
  *
  * @param id       Unique ID generated by the SASmeta server.
  * @param name     The display name
  * @param accesses The accesses IDs targeting the library
  * @param tree     The virtual folder ID containing the library.
  */
case class Library(id: String, name: String, accesses: Seq[String], tree: String)

object Library extends Factory {
    def buildCollection(xmlModel: Elem): Map[String, Library] = {
        val nodeSeq = xmlModel \\ "Objects" \ "SASLibrary"
        nodeSeq.map(buildElement).toMap
    }

    def buildElement(node: Node): (String, Library) = {
        getId(node) -> Library(getId(node),
            getName(node),
            getAccessControls(node),
            getParentTree(node)
        )
    }


}